apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sslackevent
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: k8sslackevent
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8sslackevent
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: k8sslackevent
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8sslackevent
  apiGroup: rbac.authorization.k8s.io
